services:
  victim:
    image: php:8.0-cli
    volumes:
      - ./victim-server:/var/www/html
    working_dir: /var/www/html
    command: bash -c "php -S ${HOST}:${VICTIM_PORT} -t /var/www/html"
    ports:
      - "${VICTIM_PORT}:${VICTIM_PORT}"
    environment:
      - VICTIM_PORT=${VICTIM_PORT}
    hostname: ${VICTIM_HOST}

  attacker:
    image: php:8.0-cli
    volumes:
      - ./attacker-server:/var/www/html
    working_dir: /var/www/html
    command: bash -c "php -S ${HOST}:${ATTACKER_PORT} -t /var/www/html"
    ports:
      - "${ATTACKER_PORT}:${ATTACKER_PORT}"
    environment:
      - ATTACKER_PORT=${ATTACKER_PORT}
    hostname: ${ATTACKER_HOST}
